### ISSUE TITLE
SBT JNI Classes not available after publishing jar(s)

### ISSUE THREAD

**Issue by chitralverma** [sbt/sbt-jni#134]
SBT JNI Classes not available after publishing jar(s) even though the following is set,

`sbtJniCoreScope := Compile,`

Any solutions for this except for using assembly plugin ?

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/sbt/jni/syntax/NativeLoader
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.a.b.c..version(Test.scala)
	at org.a.b.c.Main.main(Main.java:6)
Caused by: java.lang.ClassNotFoundException: com.github.sbt.jni.syntax.NativeLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 26 more
```

**Comment by pomadchin** [comment]
Hello @chitralverma, `sbtJniCoreScope := Compile` setting should be enough. 
I'm using this plugin [here](https://github.com/PDAL/java/blob/main/build.sbt#L73) and [it keeps the dependency](https://mvnrepository.com/artifact/io.pdal/pdal_2.13/2.4.0) after the release. 

Mb you could share the project structure that causes this problem? I.e. a minimized project that allows to reproduce the error happening.

**Comment by chitralverma** [comment]
Hi @pomadchin , If you download the jar from [here](https://repo1.maven.org/maven2/io/pdal/pdal_2.13/2.4.0/pdal_2.13-2.4.0.jar), and run the command below, you will see that the class `NativeLoader` does not exist in the jar.

`java -jar <path to downloaded jar>`

im running `+ publishLocal` in sbt shell and picking up my jar from `~/.ivy2/local/ ... `

**Comment by pomadchin** [comment]
It is a transitive dependency, you can use SBT to configure the PDAL dependency in this case and it will pull down sbt-jni-core from maven central. 

I'd recommend you to get familiar with https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#Managed+Dependencies

**Comment by chitralverma** [comment]
yea I saw that it's present in the generated pom.

Thanks, closing this.
