### ISSUE TITLE
Mac M1 nativeCompile not working

### ISSUE THREAD

**Issue by nkohen** [sbt/sbt-jni#91]
I cloned https://github.com/sbt/sbt-jni/tree/main/plugin/src/sbt-test/sbt-jni/simple and tried to run the test and it failed to run `nativeCompile` with the following log, despite the fact that that directory does exist.

```
[info] Building library with native build tool CMake
[error] java.io.IOException: Cannot run program "cmake" (in directory "/Users/nkohen/dev/sbt-jni/plugin/src/sbt-test/sbt-jni/simple/native/target/native/arm64-darwin/build"): error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:147)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:113)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.cmakeVersion$lzycompute(CMake.scala:26)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.cmakeVersion(CMake.scala:25)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.configure(CMake.scala:45)
[error] 	at com.github.sbt.jni.build.ConfigureMakeInstall$Instance.library(ConfigureMakeInstall.scala:31)
[error] 	at com.github.sbt.jni.build.ConfigureMakeInstall$Instance.library$(ConfigureMakeInstall.scala:26)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.library(CMake.scala:17)
[error] 	at com.github.sbt.jni.plugins.JniNative$.$anonfun$settings$14(JniNative.scala:115)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[error] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[error] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:147)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:113)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.cmakeVersion$lzycompute(CMake.scala:26)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.cmakeVersion(CMake.scala:25)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.configure(CMake.scala:45)
[error] 	at com.github.sbt.jni.build.ConfigureMakeInstall$Instance.library(ConfigureMakeInstall.scala:31)
[error] 	at com.github.sbt.jni.build.ConfigureMakeInstall$Instance.library$(ConfigureMakeInstall.scala:26)
[error] 	at com.github.sbt.jni.build.CMake$$anon$1.library(CMake.scala:17)
[error] 	at com.github.sbt.jni.plugins.JniNative$.$anonfun$settings$14(JniNative.scala:115)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (native / nativeCompile) java.io.IOException: Cannot run program "cmake" (in directory "/Users/nkohen/dev/sbt-jni/plugin/src/sbt-test/sbt-jni/simple/native/target/native/arm64-darwin/build"): error=2, No such file or directory
```

Is m1 mac not yet supported or is something else the matter?

**Comment by pomadchin** [comment]
Hey @nkohen, a great question. Unfortunately I don't own arm mac at this point and can't help you much with debugging this issue.

**Comment by nkohen** [comment]
turns out I mis-read the error and it was actually telling me I didn't have `cmake` installed (which I thought I had), no issue here :)
